services:
  easyrubero-web:
    build: .
    container_name: easyrubero_web
    restart: always
    network_mode: "host"
    volumes:
      - ./.env:/app/.env
    ports:
      - "1999:1999"
    environment:
      - NODE_ENV=production
      - PORT=1999
